services:
  debian:
    container_name: debian
    build:
      context: .
      dockerfile: c_debian/Dockerfile
      secrets:
        - id_rsa
        - id_rsa_pub

    stdin_open: true
    tty: true
    volumes:
      - ~/shared:/shared
    deploy:
      resources:
        limits:
          cpus: '14'

secrets:
  id_rsa:
    file: /home/compromyse/.ssh/id_rsa
  id_rsa_pub:
    file: ~/.ssh/id_rsa.pub
