services:
  main:
    build:
      context: ../../
      dockerfile: containers/debian/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ~/.ssh:/home/compromyse/.ssh
      - ~/shared:/shared
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 56gb
